In [2]:
import os
import pandas
import numpy
import utils
import tensorflow as tf
import tflearn
from amino_acid import Data

curr_dir = os.path.dirname(os.getcwd())
path_to_data = curr_dir + '/mhcPreds/data/'
tensorboard_path = curr_dir + '/mhcPreds/tensorboard/'
models_path = curr_dir + '/mhcPreds/models/'


train_dat = Data(path_to_data + 'train.txt', allele='HLA-A-0101')
test_dat = Data(path_to_data + 'test.txt', allele='HLA-A*01:01')


onehot, aff_one_hot, idx_one_hot = train_dat.one_hot_encoding(kmer_size=9)
test_onehot, test_aff_one_hot, test_idx_one_hot = test_dat.one_hot_encoding(kmer_size=9)


"""
kmer, aff_kmer, idx_kmer = train_dat.kmer_index_encoding(kmer_size=9)
aff_kmer = utils.ic50_to_regression_target(aff_kmer, max_ic50=50000)
aff_one_hot = utils.ic50_to_regression_target(aff_one_hot, max_ic50=50000)
"""

xTr, xTe, yTr, yTe = onehot, test_onehot, aff_one_hot, test_aff_one_hot
yTr = numpy.reshape(yTr, (yTr.shape[0], 1))
yTe = numpy.reshape(yTe, (yTe.shape[0], 1))
xTr = numpy.reshape(xTr, (xTr.shape[0], xTr.shape[1], xTr.shape[2], 1))
xTe = numpy.reshape(xTe, (xTe.shape[0], xTe.shape[1], xTe.shape[2], 1))
    

/Users/carlomazzaferro/anaconda/envs/MHC_NN/lib/python3.5/site-packages/matplotlib/__init__.py:1085: UserWarning: Duplicate key in file "/Users/carlomazzaferro/.matplotlib/matplotlibrc", line #2
  (fname, cnt))


In [7]:
fs = xTr[0, :, :]

In [14]:
fsv

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 

In [25]:
fsv = numpy.reshape(fs, (20,9))
idx = numpy.array(list(zip(numpy.nonzero(fsv)[0], numpy.nonzero(fsv)[1]))).astype('int')
idx

array([[ 0,  0],
       [ 2,  2],
       [ 6,  0],
       [ 7,  2],
       [10,  2],
       [11,  6],
       [14,  7],
       [16,  6],
       [18,  7]])

In [23]:
values = numpy.ones(9).astype(int)
values

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [24]:
sparse = tf.SparseTensor(idx, values, dense_shape=[9,20])

In [26]:

batch_size = 75
epochs = 1500
lr = 0.00001

network = tflearn.input_data(shape=[None, 9, 20, 1])
network = tflearn.dropout(network, 0.4)
print(type(network.))
loss = tflearn.fully_connected(network, 1, activation='sigmoid')
network = tflearn.regression(loss, optimizer='momentum', learning_rate=0.001)
model = tflearn.DNN(network, checkpoint_path=tensorboard_path, max_checkpoints=1, tensorboard_verbose=3)
model.fit(xTr, yTr, n_epoch=1000, validation_set=0.1, shuffle=True,
          show_metric=True, batch_size=64)

<class 'tensorflow.python.framework.ops.Tensor'>


IndexError: list index out of range

In [106]:
yTe_scoring

array([ 0.32163885,  0.32163885,  0.32163885, ...,  0.33125994,
        0.08468665,  0.08468665])

In [8]:
import pandas
preds = [regression_target_to_ic50(i[0]) for i in preds]
targs = [regression_target_to_ic50(i[0]) for i in yTe]
pandas.DataFrame([preds, targs]).T

0             1
0      322.757333   1540.276452
1      298.288057   1540.276452
2      281.972457   1540.276452
3      272.610725   1540.276452
4      396.318246   1540.276452
5      330.758850   1540.276452
6      358.977761   1540.276452
7      266.020782   1540.276452
8      246.968689   1540.276452
9     3648.759284   1540.276452
10     415.178701  13599.816872
11     327.454453  13599.816872
12     367.623100  13599.816872
13     391.426170  13599.816872
14     442.090579  13599.816872
15     421.086801  13599.816872
16     364.295493  13599.816872
17     314.434912  13599.816872
18     581.353854  13599.816872
19    3060.669472  13599.816872
20    1656.072883  31449.651043
21    1900.729486  31449.651043
22    1640.477378  31449.651043
23    1637.549448  31449.651043
24    1571.705686  31449.651043
25    1570.270567  31449.651043
26    2158.752577  31449.651043
27    1863.079455  31449.651043
28    1387.991160  31449.651043
29    1976.868453  31449.651043
...           ...           ...
2619  2923.323954   5000.000000
2620  2247.132255     13.674191
2621  2775.990625  50000.000000
2622  2810.530207    293.175201
2623   189.546631    177.584151
2624  3254.275541    900.000000
2625  2008.335387   5000.000000
2626  2283.701447  50000.000000
2627   583.431053  20000.000000
2628  2738.948836  21966.406542
2629  1637.632352    311.960710
2630  1646.917615    262.708226
2631  1037.227986   1072.085943
2632  1705.046160    941.770319
2633   301.939257    128.159011
2634  2360.479926   1015.743556
2635  1123.645011    445.670256
2636  2257.707934     29.954513
2637  1890.189988  50000.000000
2638   261.758764      2.000000
2639  2160.607783   5719.371446
2640  1659.786261   6450.335425
2641  3332.723110  50000.000000
2642  3087.824107  50000.000000
2643  3172.160511  47365.238990
2644    62.820769    778.000000
2645  2304.881162  50000.000000
2646   738.500304   1388.000000
2647   132.499003  20000.000000
2648   599.505415  20000.000000

[2649 rows x 2 columns]

In [11]:
numpy.max(xTe)

20

In [5]:
import pandas
ps = model.predict(xTe)
preds = [regression_target_to_ic50(i[0]) for i in ps]
targs = [regression_target_to_ic50(i[0]) for i in yTe]
pandas.DataFrame([preds, targs]).T


0             1
0     13779.433073  20000.000000
1      9219.578326  50000.000000
2       986.525863   3106.005166
3      1236.310011  50000.000000
4      3050.660671  20000.000000
5      1948.502773  20000.000000
6        11.198050     33.000000
7        41.551778   1194.731086
8      4758.773243  13633.749813
9        29.460669     22.629947
10      125.804885  11977.499602
11      412.540918   6326.407964
12     1244.955004    232.949887
13     4577.345061  50000.000000
14       82.394526     66.123767
15     4068.927272    766.997171
16      658.946843  37806.315838
17     2702.968660  42593.702731
18     2042.609800  50000.000000
19     6692.101902  10999.568440
20     1668.691804  20000.000000
21     9257.371204  20000.000000
22     1509.116598  25052.980441
23      224.821923  20000.000000
24      620.174833  20000.000000
25     6746.355498  30603.094807
26     2965.557535  50000.000000
27     2828.982322  20000.000000
28       42.312515  41623.000000
29     1145.429550  23265.413115
...            ...           ...
2144   7643.386013  20000.000000
2145   2872.170143  48242.236157
2146   1219.038526   2830.055894
2147   9462.043190  20000.000000
2148   1513.688506  50000.000000
2149   6434.791730  28676.966734
2150   6919.714035  20000.000000
2151    791.785652  12878.837824
2152  10454.980874  50000.000000
2153   2084.537084    834.938284
2154   4958.198178  50000.000000
2155     22.657123    120.000000
2156   8834.329317  48323.277769
2157     59.968730     80.561206
2158  15825.683799  50000.000000
2159    568.698170  34499.992410
2160    219.441042  14013.135905
2161   4127.381436  50000.000000
2162     35.374105    575.749722
2163    182.168935     29.319883
2164     11.173357     31.257375
2165   3495.495366     30.000000
2166    508.460647   7132.000000
2167     73.845190    472.347552
2168   4192.278273  50000.000000
2169    115.993362   9074.948218
2170  10982.787116  50000.000000
2171   4832.740600  20000.000000
2172   1240.003063  50000.000000
2173   5745.390219  50000.000000

[2174 rows x 2 columns]